### ISSUE TITLE
Can you control which pods are returned?

### ISSUE THREAD

**Issue by shenkev** [clux/wolfram-alpha#6]
The official API for Wolfram supports controlling which pods are returned in order to reduce computation time.

http://products.wolframalpha.com/docs/WolframAlpha-API-Reference.pdf
section: Controlling Which Pods Are Returned

Does this module support the same thing?

**Comment by clux** [comment]
It does look like these things are just passed in as part of the query string in the query.
We serialise the `qp` object on the class instance in https://github.com/clux/wolfram-alpha/blob/5e3a2c21126c2f090779d153029e01955d60653c/wolfram.js#L52

So you should be able to reach into `client.qp` and add attributes for the query itself or you can add them all in the constructor as `opts` because they get created there: https://github.com/clux/wolfram-alpha/blob/5e3a2c21126c2f090779d153029e01955d60653c/wolfram.js#L5-L16

**Comment by shenkev** [comment]
Ok thanks!
